name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: ${{ github.repository }}
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup pnpm
      uses: pnpm/actions-setup@v4
      with:
        version: 9

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.15.0'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Build VuePress site
      run: pnpm build

    - name: Upload build artifact for Pages
      uses: actions/upload-pages-artifact@v3
      with:
        name: "${{ github.repository }} VuePress build"
        path: docs/.vuepress/dist
    
    - name: Deploy to Pages
      id: deployment
      uses: actions/deploy-pages@v4